# Generated by Django 3.0.6 on 2020-06-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lives_in',
            field=models.CharField(default='', max_length=30),
        ),
    ]
