# Generated by Django 3.0.6 on 2020-06-18 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lives_in',
        ),
    ]
